/* eslint-disable */
// @ts-nocheck
/* jshint ignore:start */
/* jslint ignore:start */

/**
 * testRequest - Request Class
 * Auto-generated by ArtisanJs
 * app\Http\requests\testRequest.js
 * 
 * @fileoverview Laravel-like syntax is supported by the framework preprocessor
 * The preprocessor in boot.js converts:
 * - public function methodName() → methodName()
 * - private function methodName() → #methodName()
 * - protected function methodName() → _methodName()
 */

class testRequest extends FormRequest {
    /**
     * Authorization
     */
    public function authorize() {
        return false;
    }

    /**
     * Rules
     * You can use string, array, or function format
     */
    public function rules() {
        return {
        // Example: String format
        // name: 'required|min:3|max:50',
        
        // Example: Array format
        // email: ['required', 'email'],
        };
    }

    /**
     * Custom messages (Multi-language support)
     * Uses translation system - messages will be translated based on current locale
     * You can use: trans(), __(), or lang() - all work the same way
     */
    public function messages() {
        return {
            // 'field.rule': trans('validation.required', {attribute: trans('validation.attributes.field')})
    };
    }

    /**
     * Custom field attributes (Multi-language support)
     * Uses translation system - attributes will be translated based on current locale
     * You can use: trans(), __(), or lang() - all work the same way
     */
    public function customAttributes() {
        return {
            // field: trans('validation.attributes.field')
        };
    }
}
