/* eslint-disable */
// @ts-nocheck
/* jshint ignore:start */
/* jslint ignore:start */

/**
 * UserRequest - Request Class
 * Auto-generated by ArtisanJs
 * app/Http/requests/UserRequest.js
 * 
 * @fileoverview Laravel-like syntax is supported by the framework preprocessor
 * The preprocessor in boot.js converts:
 * - public function methodName() → methodName()
 * - private function methodName() → #methodName()
 * - protected function methodName() → _methodName()
 */

class UserRequest extends FormRequest {
    /**
     * Authorization
     */
    public function authorize() {
        return true;
    }

    /**
     * Rules
     * You can use string, array, or function format
     */
    public function rules() {
        return {
            name: 'required|min:3|max:50',
            email: ['required', 'email'],
            avatar: 'image|mimes:jpeg,png,jpg|max:2048'
        };
    }

    /**
     * Custom messages (Multi-language support)
     * Uses translation system - messages will be translated based on current locale
     * You can use: trans(), __(), or lang() - all work the same way
     */
    public function messages() {
        return {
            // Custom messages will override default translations
            // If not specified, framework will use trans('validation.required', {attribute: 'name'})
            // You can add custom messages here if needed:
            'name.required': trans('validation.required', {attribute: 'name'}),
            'name.min': trans('validation.min', {attribute: 'name', min: 3}),
            'name.max': trans('validation.max', {attribute: 'name', max: 50}),
            'email.required': trans('validation.required', {attribute: 'email'}),
            'email.email': trans('validation.email', {attribute: 'email'}),
            'avatar.image': trans('validation.image', {attribute: 'avatar'}),
            'avatar.mimes': trans('validation.mimes', {attribute: 'avatar', mimes: 'jpeg,png,jpg'}),
            'avatar.max': trans('validation.max', {attribute: 'avatar', max: 2048}),
        };
    }

    /**
     * Custom field attributes (Multi-language support)
     * Uses translation system - attributes will be translated based on current locale
     * You can use: trans(), __(), or lang() - all work the same way
     */
    public function customAttributes() {
        return {
            // field: trans('validation.attributes.field')
        };
    }
}

