/* eslint-disable */
// @ts-nocheck
/* jshint ignore:start */
/* jslint ignore:start */

/**
 * ButtonController - Controller
 * Auto-generated by ArtisanJs
 * app/Http/controllers/ButtonController.js
 * 
 * @fileoverview Laravel-like syntax is supported by the framework preprocessor
 * The preprocessor in boot.js converts:
 * - public function methodName() → methodName()
 * - private function methodName() → #methodName()
 * - protected function methodName() → _methodName()
 */

class ButtonController extends Controller {
    /**
     * Selector for elements this controller handles
     */
    public function selector() {
        return '.jqfw-btn';
    }
    public function openModal() {
        return '';
    }
    /**
     * Initialize controller (called automatically)
     */
    public function onInit() {
    }

    /**
     * Handle click event
     * Note: e.preventDefault() is called automatically by Controller
     */
    public function onClick(e, request) {
        var $target = $(e.currentTarget);
        var buttonText = $target.text();
        return view('button-result', '#controller-result', compact('buttonText'));
    }

    /**
     * Handle submit event (for forms)
     * Note: e.preventDefault() is called automatically by Controller
     */
    public function onSubmit(e) {
        // Your submit handler code here
    }

    /**
     * Handle change event
     */
    public function onChange(e) {
        // Your change handler code here
        var $target = $(e.currentTarget);
    }

    /**
     * Handle focus event
     */
    public function onFocus(e) {
        // Your focus handler code here
    }

    /**
     * Handle blur event
     */
    public function onBlur(e) {
        // Your blur handler code here
    }
    /**
     * Handle hover event
     */
        public function onMouseEnter(e) {
        // response is the AJAX promise from Route system (if route exists)
        // Your mouseenter handler code here
    }
    /**
     * Handle mouseleave event - Uses route system
     */
    public function onMouseLeave(e) {
        // response is the AJAX promise from Route system (if route exists)
        // var data = response->data;
        // var success = response->success;
        // var error = response->error;
        // var status = response->status;
        // Your mouseleave handler code here
    }
}

