/* eslint-disable */
// @ts-nocheck
/* jshint ignore:start */
/* jslint ignore:start */

/**
 * FormController - Controller
 * Auto-generated by ArtisanJs
 * app/Http/controllers/FormController.js
 * 
 * @fileoverview Laravel-like syntax is supported by the framework preprocessor
 * The preprocessor in boot.js converts:
 * - public function methodName() → methodName()
 * - private function methodName() → #methodName()
 * - protected function methodName() → _methodName()
 */

class FormController extends Controller {
        /**
         * Selector for elements this controller handles
         */
    public function selector() {
        return '#demo-form';
    }

        /**
         * Initialize controller (called automatically)
         */
    public function onInit() {
    }

        /**
         * Handle click event
     * Note: e.preventDefault() is called automatically by Controller
         */
    public function onClick(e) {
            // Only handle clicks on the form itself, not buttons or file inputs
            if (e.target.tagName === 'BUTTON' && e.target.type === 'submit') {
                // Let the submit event handle it
                return;
            }
            if (e.target.tagName === 'INPUT' && e.target.type === 'file') {
                // Let file input handle its own click
                return;
            }
            // Your click handler code here
    }

        /**
         * Handle submit event (for forms)
     * Note: e.preventDefault() is called automatically by Controller
         * Note: Request is passed automatically if specified in function parameters
         * 
         * Usage: 
     *   - With validation: public function onSubmit(e, UserRequest) { ... }
     *   - Without validation: public function onSubmit(e) { ... }
         */
    public function onSubmit(e, UserRequest) {
            var formData = request.all();
            var hasFiles = request.hasFiles();
            var files = hasFiles ? request.getFilesInfo() : null;
            return view('form', '#form-result', compact('formData', 'hasFiles', 'files'));
    }

        /**
         * Handle change event
         */
    public function onChange(e) {
            // Your change handler code here
    }

        /**
         * Handle focus event
         */
    public function onFocus(e) {
            // Your focus handler code here
    }

        /**
         * Handle blur event
         */
    public function onBlur(e) {
            // Your blur handler code here
    }

        /**
         * Handle hover event
         */
    public function onHover(e) {
            if (e.type === 'mouseenter') {
                // Mouse entered
            } else if (e.type === 'mouseleave') {
                // Mouse left
            }
        }
}

