/* eslint-disable */
// @ts-nocheck
/* jshint ignore:start */
/* jslint ignore:start */

/**
 * Test1Controller - Controller
 * Auto-generated by ArtisanJs
 * app\Http\controllers\Test1Controller.js
 * 
 * @fileoverview Laravel-like syntax is supported by the framework preprocessor
 * The preprocessor in boot.js converts:
 * - public function methodName() → methodName()
 * - private function methodName() → #methodName()
 * - protected function methodName() → _methodName()
 */

class Test1Controller extends Controller {
    /**
     * Selector for elements this controller handles
     */
    public function selector() {
        return '#test1';
    }

    /**
     * Initialize controller (called automatically)
     */
    public function onInit() {
    }

    /**
     * Handle click event - Uses route system
     * Note: e.preventDefault() is called automatically by Controller
     */
    public function onClick(e) {
        // Your click handler code here
    }

    /**
     * Handle submit event (for forms) - Uses route system
     * Note: e.preventDefault() is called automatically by Controller
     * 
     * To use Request validation, add Request name as second parameter:
     * public function onSubmit(e, UserRequest) {
     *     // response is the AJAX promise from Route system
     *     var data = response->data;
     *     // ...
     * }
     */
    public function onSubmit(e) {
        // Your submit handler code here
    }

    /**
     * Handle change event - Uses route system
     */
    public function onChange(e) {
        // response is the AJAX promise from Route system
    }

    /**
     * Handle focus event - Uses route system
     */
    public function onFocus(e) {
        // Your focus handler code here
    }

    /**
     * Handle blur event - Uses route system
     */
    public function onBlur(e) {
        // Your blur handler code here
    }

    /**
     * Handle hover event
     */
    public function onHover(e) {
        if (e.type === 'mouseenter') {
            // Mouse entered
        } else if (e.type === 'mouseleave') {
            // Mouse left
        }
    }

    /**
     * Handle input event - Uses route system
     */
    public function onInput(e) {
        // Your input handler code here
    }

    /**
     * Handle scroll event - Uses route system
     */
    public function onScroll(e) {
        // Your scroll handler code here
    }

    /**
     * Handle keyup event - Uses route system
     */
    public function onKeyUp(e) {
        // Your keyup handler code here
    }

    /**
     * Handle keydown event - Uses route system
     */
    public function onKeyDown(e) {
        // Your keydown handler code here
    }
}

